chore: load core css in coding components samples
Esri/arcgis-maps-sdk-javascript-samples-beta pull request #20
Opened 2024-03-11 19:01 UTC by nick-romano

This PR updates the coding components samples to load the @arcgis/core styles. There were concerns that in the case that a user loaded a private webmap, they would see an unstyled dialog popup. This fixes that.

2024-03-11 19:48 UTC, andygup requested changes
Just some small changes.

2024-03-11 19:48 UTC, andygup commented on packages/coding-components/templates/angular/src/index.html
> +  <link rel="stylesheet" href="https://js.arcgis.com/4.29/esri/themes/light/main.css" />
Let's switch this to the ESM CDN and it should moved from index.html and into the component directory's .css file.

2024-03-11 19:48 UTC, andygup commented on packages/coding-components/templates/vue/src/assets/main.css
> +@import 'https://js.arcgis.com/4.29/@arcgis/core/assets/esri/themes/light/main.css';
Inconsistent double quotas versus single.

2024-03-11 19:48 UTC, andygup commented on packages/coding-components/templates/vite/style.css
> +@import 'https://js.arcgis.com/4.29/@arcgis/core/assets/esri/themes/light/main.css';
Ditto, on single quotes mixed with doubles.

2024-03-11 19:48 UTC, andygup commented on packages/coding-components/templates/webpack/src/index.css
> +@import 'https://js.arcgis.com/4.29/@arcgis/core/assets/esri/themes/light/main.css';
Ditto on single qoutes.

2024-03-20 15:30 UTC, omarkawach approved these changes

2024-03-25 21:40 UTC, merged