chore: update webpack templates for all components
Esri/arcgis-maps-sdk-javascript-samples-beta pull request #24
Opened 2024-03-25 22:09 UTC by jimmychen97

- Updated webpack templates matching Map Component's template
- Updated webpack's README to reflect new changes

2024-03-25 23:15 UTC, omarkawach approved these changes

2024-03-26 00:01 UTC, andygup requested changes
Just a few small things.

2024-03-26 00:01 UTC, andygup commented on packages/coding-components/templates/webpack/readme.md
> +The parsing of our `index.html` was simplified by using the HtmlWebpackPlugin in the webpack configuration file.
```suggestion
Parsing the `index.html` was simplified by using the HtmlWebpackPlugin in the webpack configuration file.
```

2024-03-26 16:03 UTC, andygup approved these changes
👍

2024-03-26 16:04 UTC, merged